version: '3.8'

services:
  db:
    image: postgres:14.5
    container_name: ecommerce_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce

  app:
    build: .
    container_name: ecommerce_app
    ports:
      - 4100:4100
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: ecommerce
      DB_PORT: 5432
      DB_DIALECT: postgres
      APP_PORT: 4100
    volumes:
      - ./src:/app/src
    depends_on:
      - db
